import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/header";
import newSession, { Session } from "./utils/auth";
import { redirect } from "next/navigation";
import { host } from "./components/host";
import React from "react";
import { headers } from "next/headers";
import AuthWrap from "./components/authWrap";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let name = await newSession.getName();
  // let access = await Session.setAccessToken();
  // let name = null;
  // console.log(request.url.split('/').includes('auth'));  
  // let currentUrl = await headers();
  // console.log(currentUrl);
  // let redir = !currentUrl.get('referer').split('/').includes('auth');
  // console.log(redir)
  // console.log(!currentUrl.get('referer').split('/').includes('auth'));
  // if (access) name = await newSession.getName();
  // else if (redir) redirect(`http://${host}/auth/login`, 'replace');
  if (!newSession.isAuthProccess) {
    let access = await Session.setAccessToken();
    if (access) {
        newSession.interval = setInterval(async () => {
            let newToken = await newSession.refreshToken();
            if (newToken) return;
            else {
                newSession.clearSession();
                redirect(`http://${host}/auth/login`, 'replace');
            }
        }, access.livetime);
    } else {
        newSession.clearSession();
        redirect(`http://${host}/auth/login`, 'replace');
    }
}

  return (
    <html lang="en">
      <body className="bg-light-grey">
          <Header name={name}/>
          <div className="py-[44px] tablet:py-0 tablet:pt-[90px] tablet:pb-5">
            {children}
          </div>
          <Footer />
      </body>
    </html>
  );
}

// export default RootLayout
